vich_uploader:
  db_driver: orm

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
  #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
  metadata:
    type: attribute

  mappings:
    images:
      uri_prefix: /dogImage
      upload_destination: "%kernel.project_dir%/public/images/dogImages"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      directory_namer:
        service: App\Namer\DirectoryNamer
